nix-grep

diff --git a/nix-grep b/nix-grep
--- a/nix-grep
+++ b/nix-grep
@@ -1,2 +1,9 @@
 #!/usr/bin/env bash
-exec nix-env -f $NIXPKGS -qaP \* | grep -i "$@"
+if [ ! -f $HOME/.nixenv.cache ]; then
+  >&2 echo "cache not found, generating..."
+  nix-build-cache
+  >&2 echo "done"
+  >&2 echo ""
+fi
+
+grep -i $@ $HOME/.nixenv.cache
